FILE = src/main.cpp
OUT = ray
FLAGS = -lm -fopenmp -lsfml-system -lsfml-graphics -lsfml-window -lpthread -std=c++11 -O3
CC = g++

all: compile

compile:
	$(CC) $(FILE) -o $(OUT) $(FLAGS)

.PHONY: ALL
